name: interfold-db
x-log-rotation: &default-log-rotation
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  scylla-host-aio:
    image: scylladb/scylla:2025.1
    privileged: true
    pid: host
    restart: "no"
    volumes:
      - ../dev/scylla/scripts/ensure-host-aio.sh:/scripts/ensure-host-aio.sh:ro
    entrypoint: ["/bin/bash", "/scripts/ensure-host-aio.sh"]

  scylla:
    image: scylladb/scylla:2025.1
    ports:
      - "9042:9042"
    restart: always
    command: --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla
    volumes:
      - ../dev/scylla/cassandra-rackdc.nam.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    networks:
      octo_network:
        ipv4_address: 172.30.1.1
    depends_on:
      scylla-host-aio:
        condition: service_completed_successfully
  
  scylla-load-keyspaces:
    image: scylladb/scylla:2025.1
    logging: *default-log-rotation
    depends_on:
      scylla:
        condition: service_healthy
      msg-db-load-schema:
        condition: service_completed_successfully
    volumes:
      - ../csharp/db/scylla/001_create_octocon_keyspaces.cql:/init.cql
      - ../csharp/db/scylla/001_create_octocon_schema.templated.cql:/schema.cql
      - ../dev/scylla/scripts/scylla-load-keyspaces.sh:/scripts/scylla-load-keyspaces.sh
    restart: on-failure
    entrypoint: ["/bin/bash", "/scripts/scylla-load-keyspaces.sh", "scylla"]
    networks:
      octo_network:

networks:
  octo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16

volumes:
  scylla_data:
