x-log-rotation: &default-log-rotation
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  scylla-nam:
    image: scylladb/scylla:2025.1
    ports:
      - "9042:9042"
    restart: always
    command: --seeds=172.18.1.1 --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla-nam
    volumes:
      - ../dev/scylla/cassandra-rackdc.nam.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_nam_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    networks:
      octo_network:
        ipv4_address: 172.18.1.1

  scylla-eur:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=172.18.1.1,172.18.1.2 --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla-eur
    volumes:
      - ../dev/scylla/cassandra-rackdc.eur.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_eur_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    depends_on:
      scylla-nam:
        condition: service_healthy
    networks:
      octo_network:
        ipv4_address: 172.18.1.2
  
  scylla-sam:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=172.18.1.1,172.18.1.2 --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla-sam
    volumes:
      - ../dev/scylla/cassandra-rackdc.sam.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_sam_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    depends_on:
      scylla-eur:
        condition: service_healthy
    networks:
      octo_network:
        ipv4_address: 172.18.1.3

  scylla-sas:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=172.18.1.1,172.18.1.2 --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla-sas
    volumes:
      - ../dev/scylla/cassandra-rackdc.sas.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_sas_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    depends_on:
      scylla-sam:
        condition: service_healthy
    networks:
      octo_network:
        ipv4_address: 172.18.1.4

  scylla-eas:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=172.18.1.1,172.18.1.2 --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla-eas
    volumes:
      - ../dev/scylla/cassandra-rackdc.eas.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_eas_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    depends_on:
      scylla-sas:
        condition: service_healthy
    networks:
      octo_network:
        ipv4_address: 172.18.1.5

  scylla-ocn:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=172.18.1.1,172.18.1.2 --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla-ocn
    volumes:
      - ../dev/scylla/cassandra-rackdc.ocn.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_ocn_data:/var/lib/scylla
    logging: *default-log-rotation
    depends_on:
      scylla-eas:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    networks:
      octo_network:
        ipv4_address: 172.18.1.6

  scylla-load-keyspaces:
    image: scylladb/scylla:2025.1
    depends_on:
      scylla-nam:
        condition: service_healthy
      msg-db-load-schema:
        condition: service_completed_successfully
    volumes:
      - ../dev/scylla/scripts/init.cql:/init.cql
      - ../csharp/db/scylla/001_create_octocon_schema.cql:/schema.cql
      - ../dev/scylla/scripts/scylla-load-keyspaces.sh:/scripts/scylla-load-keyspaces.sh
    restart: on-failure
    entrypoint: ["/bin/bash", "/scripts/scylla-load-keyspaces.sh", "scylla-nam", "eur", "sam", "sas", "eas", "ocn"]
    networks:
      octo_network:

  msg-db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "4200:5432"
    volumes:
      - ../msg_pgdata:/var/lib/postgresql/data
    logging: *default-log-rotation
    networks:
      octo_network:

  msg-db-load-schema:
    image: timescale/timescaledb:latest-pg16
    logging: *default-log-rotation
    depends_on:
      msg-db:
        condition: service_started
    environment:
      PGPASSWORD: postgres
    volumes:
      - ../csharp/db/postgres/001_create_octocon_idempotency.sql:/schemas/001_create_octocon_idempotency.sql:ro
      - ../csharp/db/postgres/002_create_auth_tokens.sql:/schemas/002_create_auth_tokens.sql:ro
      - ../dev/scylla/scripts/postgres-load-schema.sh:/scripts/postgres-load-schema.sh:ro
    restart: on-failure
    entrypoint:
      [
        "/bin/bash",
        "/scripts/postgres-load-schema.sh",
        "msg-db",
        "octocon",
        "postgres",
        "/schemas/001_create_octocon_idempotency.sql",
        "/schemas/002_create_auth_tokens.sql"
      ]
    networks:
      octo_network:

networks:
  octo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  scylla_nam_data:
  scylla_eur_data:
  scylla_sam_data:
  scylla_sas_data:
  scylla_eas_data:
  scylla_ocn_data: