x-log-rotation: &default-log-rotation
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  scylla:
    image: scylladb/scylla:2025.1
    ports:
      - "9042:9042"
    restart: always
    command: --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --endpoint-snitch GossipingPropertyFileSnitch --api-address 0.0.0.0 --broadcast-address scylla
    volumes:
      - ../dev/scylla/cassandra-rackdc.nam.properties:/etc/scylla/cassandra-rackdc.properties
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    logging: *default-log-rotation
    networks:
      octo_network:
        ipv4_address: 172.30.1.1

  msg-db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "4200:5432"
    volumes:
      - ../msg_pgdata:/var/lib/postgresql/data
    networks:
      octo_network:

  msg-db-load-schema:
    image: timescale/timescaledb:latest-pg16
    logging: *default-log-rotation
    depends_on:
      msg-db:
        condition: service_started
    environment:
      PGPASSWORD: postgres
    volumes:
      - ../csharp/db/postgres/001_create_octocon_idempotency.sql:/schemas/001_create_octocon_idempotency.sql:ro
      - ../csharp/db/postgres/002_create_auth_tokens.sql:/schemas/002_create_auth_tokens.sql:ro
      - ../dev/scylla/scripts/postgres-load-schema.sh:/scripts/postgres-load-schema.sh:ro
    restart: on-failure
    entrypoint:
      [
        "/bin/bash",
        "/scripts/postgres-load-schema.sh",
        "msg-db",
        "octocon",
        "postgres",
        "/schemas/001_create_octocon_idempotency.sql",
        "/schemas/002_create_auth_tokens.sql"
      ]
    networks:
      octo_network:
  
  scylla-load-keyspaces:
    image: scylladb/scylla:2025.1
    logging: *default-log-rotation
    depends_on:
      scylla:
        condition: service_healthy
      msg-db-load-schema:
        condition: service_completed_successfully
    volumes:
      - ../csharp/db/scylla/001_create_octocon_keyspaces.cql:/init.cql
      - ../csharp/db/scylla/001_create_octocon_schema.nam.cql:/schema.cql
      - ../dev/scylla/scripts/scylla-load-keyspaces.sh:/scripts/scylla-load-keyspaces.sh
    restart: on-failure
    entrypoint: ["/bin/bash", "/scripts/scylla-load-keyspaces.sh", "scylla"]
    networks:
      octo_network:

networks:
  octo_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16

volumes:
  scylla_data:
