using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.Docker.Resources.ComposeNodes;
using Aspire.Hosting.Docker.Resources.ServiceNodes;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using System.Net.Sockets;

// Deliberately *not* the assembly's matching `Interfold.AppHost` namespace - that conflicts with
// types generated by Aspire's AppHost SDK (notably `Projects.*` and a few SDK-private partial
// classes referencing the assembly name as a namespace). Use `Interfold.AppHostGraph` so the
// embedded bootstrapper can `using Interfold.AppHostGraph;` unambiguously.
namespace Interfold.AppHostGraph;

/// <summary>
/// Defines the Interfold distributed-application resource graph (Postgres, Scylla/Cassandra,
/// bootstrap-auth containers, the API, and the web container).
/// </summary>
/// <remarks>
/// Shared between two entry points:
/// <list type="bullet">
///   <item>The dev <c>Interfold.AppHost</c> executable (`aspire run` workflow).</item>
///   <item>The self-hosting <c>Interfold.Bootstrapper</c> executable, which pre-populates
///         <see cref="Microsoft.Extensions.Configuration.IConfiguration"/> with generated
///         secrets before calling <see cref="Configure"/> and then runs the publish flow
///         to emit a Docker Compose file.</item>
/// </list>
/// </remarks>
public static class InterfoldAppHost
{
    /// <summary>
    /// Registers the full Interfold resource graph on the supplied
    /// <see cref="IDistributedApplicationBuilder"/>. Does not call <c>Build()</c> or <c>Run()</c>.
    /// </summary>
    public static void Configure(IDistributedApplicationBuilder builder)
    {
        // --- Configurable host ports (must be declared before health checks reference them) ---
        int Port(string name, int fallback) => int.TryParse(builder.Configuration[$"Ports:{name}"], out var p) ? p : fallback;
        var postgresPort = Port("postgres", 4200);
        var scyllaPort = Port("scylla", 9042);
        // Cassandra has its own port slot so a single host can publish both Scylla and Cassandra
        // when the integration test SharedDbFixture asks for both. The legacy bootstrapper path
        // (only-cassandra-on-Ports:scylla) is preserved further down by falling back to
        // scyllaPort when Cassandra runs alone.
        var cassandraPort = Port("cassandra", 9043);
        var apiHttpPort = Port("api-http", 5000);
        var apiHttpsPort = Port("api-https", 5001);
        var webHttpPort = Port("web-http", 8080);
        var webHttpsPort = Port("web-https", 8081);

        // --- Optional feature flags (used by integration tests to disable API/web and use ephemeral containers) ---
        var includeApi = !string.Equals(builder.Configuration["Parameters:include-api"], "false", StringComparison.OrdinalIgnoreCase);
        var persistentContainers = !string.Equals(builder.Configuration["Parameters:persistent-containers"], "false", StringComparison.OrdinalIgnoreCase);

        // --- Per-resource toggles ---
        // The integration test SharedDbFixture flips these on/off based on which fixtures the
        // current test session actually requires (scanned via TUnit's TestSessionContext). Both
        // can be true at once so we run Scylla and Cassandra side-by-side under one Aspire host.
        // For back-compat, when neither toggle is set, fall back to the legacy `scylla-mode`
        // parameter (which the bootstrapper still drives via PublishPhase). The single switch
        // also drives Scylla's internal topology (single-node vs 7-region multi-DC).
        var scyllaMode = builder.Configuration["Parameters:scylla-mode"] ?? "single";
        var isMultiScylla = string.Equals(scyllaMode, "multi", StringComparison.OrdinalIgnoreCase);
        var includeScylla = ParseToggle(
            builder.Configuration["Parameters:include-scylla"],
            fallback: string.Equals(scyllaMode, "single", StringComparison.OrdinalIgnoreCase) || isMultiScylla);
        var includeCassandra = ParseToggle(
            builder.Configuration["Parameters:include-cassandra"],
            fallback: string.Equals(scyllaMode, "cassandra", StringComparison.OrdinalIgnoreCase));

        static bool ParseToggle(string? raw, bool fallback)
            => string.IsNullOrEmpty(raw)
                ? fallback
                : !string.Equals(raw, "false", StringComparison.OrdinalIgnoreCase);

        // --- Health checks for the Aspire dashboard (only when API is included) ---
        // In test mode (include-api=false), Aspire randomizes host ports, so TcpClient
        // health checks would fail. Without health checks, WaitFor() uses Running state.
        if (includeApi)
        {
            builder.Services.AddHealthChecks()
                .AddCheck("msg-db-health", () =>
                {
                    try
                    {
                        using var tcp = new TcpClient();
                        tcp.Connect("localhost", postgresPort);
                        return HealthCheckResult.Healthy();
                    }
                    catch { return HealthCheckResult.Unhealthy(); }
                })
                .AddCheck("scylla-health", () =>
                {
                    try
                    {
                        using var tcp = new TcpClient();
                        tcp.Connect("localhost", scyllaPort);
                        return HealthCheckResult.Healthy();
                    }
                    catch { return HealthCheckResult.Unhealthy(); }
                });
        }

        // --- Docker Compose publish target with network isolation ---
        // The bootstrapper sets `Parameters:include-dashboard=false` because the Aspire dashboard
        // resource pulls `mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest` at compose-up
        // time, which is not appropriate for self-hosted production stacks (network egress to MCR,
        // nightly image churn). The dev `aspire run` workflow keeps the dashboard.
        var includeDashboard = !string.Equals(builder.Configuration["Parameters:include-dashboard"], "false", StringComparison.OrdinalIgnoreCase);
        builder.AddDockerComposeEnvironment("docker-compose")
            .WithDashboard(includeDashboard)
            .ConfigureComposeFile(compose =>
            {
                compose.AddNetwork(new Network { Name = "scylla", Driver = "bridge" });
                compose.AddNetwork(new Network { Name = "postgres", Driver = "bridge" });
                compose.AddNetwork(new Network { Name = "api", Driver = "bridge" });

                // Dashboard needs to be reachable by API for OTLP telemetry
                if (compose.Services.TryGetValue("docker-compose-dashboard", out var dashboard))
                {
                    dashboard.Networks.Add("api");
                }
            });

        // --- Parameters (set via user-secrets or environment variables) ---
        var postgresUser = builder.AddParameter("postgres-user");
        var postgresPassword = builder.AddParameter("postgres-password", secret: true);
        // Transient init credential. POSTGRES_USER on the msg-db service is hard-coded to
        // "db_init" - a disposable cluster-owner that the bootstrapper's DatabaseInitPhase uses
        // exactly once to create the real app + admin roles, then ALTERs to a fresh random
        // password we don't persist anywhere. The .env value sitting in the operator's
        // deployment dir is intentionally stale by the time the API starts.
        //
        // Default value: GenerateParameterDefault produces a random 24-char password on first
        // run and persists it to user-secrets (persist: true) so `aspire run` and the
        // TUnit.Aspire integration tests can spin up the resource graph without the developer
        // pre-seeding `Parameters:postgres-init-password`. In publish mode the bootstrapper's
        // PublishPhase.BuildEnvReplacements overrides this value with the one in secrets.json
        // before the .env file is materialised, so the generated default never leaks into a
        // production deployment.
        var postgresInitPassword = builder.AddParameter("postgres-init-password",
            new GenerateParameterDefault { MinLength = 24 }, secret: true, persist: true);
        var scyllaUser = builder.AddParameter("scylla-user");
        var scyllaPassword = builder.AddParameter("scylla-password", secret: true);
        // The matching `<user>_admin` role is created by the bootstrapper's DatabaseInitPhase with
        // a freshly generated password that lives only inside internal.secrets - it is never
        // surfaced as an AppHost parameter or compose env var.
        var encryptionPrivateKey = builder.AddParameter("encryption-private-key", secret: true);
        // The encryption pepper moved into internal.secrets:encryption:pepper.
        // SecretsBootstrapService patches AuthenticationConfiguration.EncryptionPepper at
        // startup and refuses to boot the API if the row is missing.
        // The leaf PFX password moved into internal.secrets:certs:leaf_pfx_password.
        // Program.cs runs a one-shot Npgsql query to load it into the Kestrel default-cert
        // configuration before the HTTPS endpoint binds, so the AppHost no longer needs a
        // parameter for it.

        // --- Reject well-known default passwords at startup (dev mode only; compose relies on shell guard) ---
        if (!builder.ExecutionContext.IsPublishMode)
        {
            var scyllaPasswordValue = builder.Configuration["Parameters:scylla-password"];
            if (string.IsNullOrEmpty(scyllaPasswordValue) || scyllaPasswordValue == "cassandra")
            {
                throw new InvalidOperationException(
                    "SCYLLA_PASSWORD must be set to a non-default value. " +
                    "The well-known default 'cassandra' is not allowed.\n" +
                    "Fix: dotnet user-secrets set \"Parameters:scylla-password\" \"<your-secure-password>\" " +
                    "--project csharp/Interfold.AppHost");
            }

            var scyllaUserValue = builder.Configuration["Parameters:scylla-user"];
            if (string.IsNullOrEmpty(scyllaUserValue) || scyllaUserValue == "cassandra")
            {
                throw new InvalidOperationException(
                    "SCYLLA_USER must be set to a non-default value. " +
                    "The well-known default 'cassandra' is not allowed.\n" +
                    "Fix: dotnet user-secrets set \"Parameters:scylla-user\" \"<your-username>\" " +
                    "--project csharp/Interfold.AppHost");
            }

            var postgresPasswordValue = builder.Configuration["Parameters:postgres-password"];
            if (string.IsNullOrEmpty(postgresPasswordValue) || postgresPasswordValue == "postgres")
            {
                throw new InvalidOperationException(
                    "POSTGRES_PASSWORD must be set to a non-default value. " +
                    "The well-known default 'postgres' is not allowed.\n" +
                    "Fix: dotnet user-secrets set \"Parameters:postgres-password\" \"<your-secure-password>\" " +
                    "--project csharp/Interfold.AppHost");
            }

            var postgresUserValue = builder.Configuration["Parameters:postgres-user"];
            if (string.IsNullOrEmpty(postgresUserValue) || postgresUserValue == "postgres")
            {
                throw new InvalidOperationException(
                    "POSTGRES_USER must be set to a non-default value. " +
                    "The well-known default 'postgres' is not allowed.\n" +
                    "Fix: dotnet user-secrets set \"Parameters:postgres-user\" \"<your-username>\" " +
                    "--project csharp/Interfold.AppHost");
            }
        }

        // --- PostgreSQL (TimescaleDB) ---
        // First-boot pattern (least-privilege):
        //   - `POSTGRES_USER=db_init`: postgres creates db_init as the bootstrap superuser
        //     (OID 10). We can't ever demote that role per postgres' own hard-coded restriction
        //     (commands/user.c::AlterRole), so we use a disposable name for it.
        //   - `POSTGRES_PASSWORD=${POSTGRES_INIT_PASSWORD}`: the transient init credential.
        //     DatabaseInitPhase consumes it once to mint the real app + admin roles, then
        //     scrambles db_init's password to a fresh random value the bootstrapper does not
        //     persist. The compose .env value is therefore stale by the time the API starts.
        //   - No `POSTGRES_DB`: DatabaseInitPhase creates the `octocon` database owned by the
        //     admin role, not by db_init - keeps DDL gating consistent.
        //
        // The interfold-api connection string below references `${POSTGRES_USER}` /
        // `${POSTGRES_PASSWORD}` which resolve to the *app* user (interfold), not db_init. So the
        // only PostgreSQL connection string in the compose graph is the app's.
        var msgDb = builder.AddContainer("msg-db", "timescale/timescaledb", "latest-pg18")
            .WithContainerNetworkAlias("msg-db")
            .WithEnvironment("POSTGRES_USER", "db_init")
            .WithEnvironment("POSTGRES_PASSWORD", postgresInitPassword)
            .WithEnvironment("PGDATA", "/var/lib/postgresql/data/pgdata")
            // initdb's default --auth-host is `trust`, which produces `host all all 127.0.0.1/32 trust`
            // in pg_hba.conf BEFORE the entrypoint appends `host all all all scram-sha-256`. With
            // first-match-wins ordering, TCP loopback connections (e.g. `psql -h 127.0.0.1` from
            // inside the container) silently bypass the password check — defeating the bootstrapper's
            // db_init password scramble. Forcing scram-sha-256 for every host entry closes that
            // loophole and matches the security posture the rest of the stack assumes.
            //
            // Unix socket connections still use `local all all trust`, which is what the bootstrapper's
            // DatabaseInitPhase relies on (it connects as db_init via the socket to mint the app +
            // admin roles before the password is scrambled).
            .WithEnvironment("POSTGRES_INITDB_ARGS", "--auth-host=scram-sha-256")
            // Bump pg_ctl's wait timeout from the 60s default. The postgres image entrypoint
            // does `pg_ctl -m fast -w stop` after the timescaledb-tune init script runs, then
            // re-execs postgres in normal mode. On slow Docker-in-Docker disks the shutdown
            // checkpoint can take well past 60s, which makes the entrypoint exit with
            // "pg_ctl: server does not shut down" and the container die before the bootstrapper's
            // WaitForPostgresAsync ever sees normal mode. 300s gives us comfortable headroom.
            .WithEnvironment("PGCTLTIMEOUT", "300")
            // timescaledb-tune (the image's 001_timescaledb_tune.sh init script) reads
            // /sys/fs/cgroup/memory.max to size shared_buffers. Self-hosting hosts running on
            // Docker Desktop / cgroup-v2-restricted environments may not expose that file, in
            // which case the tune script panics and the container exits during init. Setting
            // TS_TUNE_MEMORY + TS_TUNE_NUM_CPUS bypasses auto-detection with safe conservative
            // defaults; operators on bigger boxes can override these env vars in a
            // docker-compose.override.yaml without re-running the bootstrapper.
            .WithEnvironment("TS_TUNE_MEMORY", "1GB")
            .WithEnvironment("TS_TUNE_NUM_CPUS", "2")
            .WithEndpoint(port: postgresPort, targetPort: 5432, name: "postgres", scheme: "tcp")
            .PublishAsDockerComposeService((_, service) =>
            {
                service.Networks = ["postgres"];
                service.Healthcheck = new Healthcheck
                {
                    Test = ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d postgres"],
                    Interval = "10s",
                    Timeout = "5s",
                    Retries = 10,
                    StartPeriod = "15s"
                };
            });
        if (includeApi)
            msgDb.WithHealthCheck("msg-db-health");
        if (persistentContainers)
        {
            msgDb.WithVolume("msg_pgdata", "/var/lib/postgresql/data");
            msgDb.WithLifetime(ContainerLifetime.Persistent);
        }

        // --- ScyllaDB / Cassandra (independent toggles, can both be on at once) ---
        // Resources the API container needs to wait on before starting. Populated below as each
        // included CQL backend stands up. When both are on, the API depends on both.
        var cqlEndpointOwners = new List<IResourceBuilder<ContainerResource>>();

        if (includeScylla)
        {
            // --- ScyllaDB nodes (single or multi based on scylla-mode) ---
            string[] regions = isMultiScylla
                ? ["nam", "eur", "sam", "sas", "eas", "ocn", "gdpr"]
                : ["nam"];

            IResourceBuilder<ContainerResource>? previousNode = null;

            foreach (var region in regions)
            {
                var name = regions.Length > 1 ? $"scylla-{region}" : "scylla";
                var seeds = previousNode is null ? $"--seeds={name}" : $"--seeds=scylla-{regions[0]},scylla-{regions[1]}";

                var node = builder.AddContainer(name, "scylladb/scylla", "2026.1")
                    .WithContainerNetworkAlias(name)
                    .WithArgs(seeds, "--smp", "1", "--memory", "750M", "--overprovisioned", "1",
                        "--developer-mode", "1", "--authenticator", "PasswordAuthenticator",
                        "--authorizer", "CassandraAuthorizer",
                        "--endpoint-snitch", "GossipingPropertyFileSnitch",
                        "--api-address", "0.0.0.0", "--broadcast-address", name)
                    .WithBindMount($"../../db/scylla/cassandra-rackdc.{region}.properties", "/etc/scylla/cassandra-rackdc.properties", isReadOnly: true)
                    .WithEnvironment("CQLSH_USER", scyllaUser)
                    .WithEnvironment("CQLSH_PASSWORD", scyllaPassword)
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["scylla"];
                        // `nodetool status` returning UN means gossip-bootstrap is done, but the
                        // CQL listener can come up several seconds later (we've observed gaps of
                        // 60–90s on slow DinD hosts between NORMAL mode and "Starting listening
                        // for CQL clients on ...:9042"). Probe the actual CQL endpoint with the
                        // app role so depends_on:service_healthy really means "CQL is reachable
                        // as the app user". Pre-bootstrap (before DatabaseInitPhase has minted
                        // the role) this probe fails, but the API doesn't depend on this
                        // healthcheck during that window — the bootstrapper uses its own
                        // WaitForScyllaAsync against the default cassandra session instead.
                        //
                        // The doubled `$$` is intentional: docker-compose interpolates `${VAR}`
                        // and `$VAR` at YAML-parse time using host-shell env vars, which is NOT
                        // what we want for healthcheck commands. `$$VAR` escapes to a literal
                        // `$VAR` that the container's `/bin/sh -c` will expand against the
                        // container's own env (where CQLSH_USER / CQLSH_PASSWORD are set).
                        service.Healthcheck = new Healthcheck
                        {
                            Test = ["CMD-SHELL",
                                "cqlsh -u \"$$CQLSH_USER\" -p \"$$CQLSH_PASSWORD\" -e 'DESCRIBE CLUSTER' >/dev/null 2>&1"],
                            Interval = "15s",
                            Timeout = "10s",
                            Retries = 20,
                            StartPeriod = "30s"
                        };
                    });

                if (persistentContainers)
                {
                    node.WithVolume(regions.Length > 1 ? $"scylla_{region}_data" : "scylla_data", "/var/lib/scylla");
                    node.WithLifetime(ContainerLifetime.Persistent);
                }

                if (previousNode is null)
                {
                    node.WithEndpoint(port: scyllaPort, targetPort: 9042, name: "cql", scheme: "tcp");
                    if (includeApi) node.WithHealthCheck("scylla-health");
                    cqlEndpointOwners.Add(node);
                }
                else
                    node.WaitFor(previousNode);

                previousNode = node;
            }
        }

        if (includeCassandra)
        {
            // --- Cassandra 5 ---
            // Built from db/cassandra/Dockerfile (FROM cassandra:5), which bakes the
            // cassandra.yaml overrides we need (materialized_views_enabled,
            // PasswordAuthenticator, CassandraAuthorizer) into the image at build time. That
            // removes the need for a runtime wrapper script and avoids the bind-mount/chown
            // pitfalls that previously broke Cassandra on GHA. Datacenter/rack are set via env
            // vars; the official entrypoint writes them into cassandra-rackdc.properties using
            // an in-place rewrite that does not rename.
            //
            // Endpoint port: when running alone (legacy bootstrapper "cassandra mode") the
            // operator's compose .env writes `Ports:scylla=9042` and Cassandra binds there for
            // back-compat. When running alongside Scylla under the integration test
            // SharedDbFixture, both toggles are on and Cassandra uses its own `Ports:cassandra`
            // slot (default 9043) so the two CQL listeners don't collide.
            var cassandraEndpointPort = includeScylla ? cassandraPort : scyllaPort;

            var cassandra = builder.AddDockerfile("cassandra", "../../db/cassandra")
                .WithContainerNetworkAlias("cassandra")
                .WithEnvironment("CASSANDRA_CLUSTER_NAME", "OctoCluster")
                .WithEnvironment("CASSANDRA_LISTEN_ADDRESS", "cassandra")
                .WithEnvironment("CASSANDRA_BROADCAST_ADDRESS", "cassandra")
                .WithEnvironment("CASSANDRA_BROADCAST_RPC_ADDRESS", "cassandra")
                .WithEnvironment("CASSANDRA_RPC_ADDRESS", "0.0.0.0")
                .WithEnvironment("CASSANDRA_ENDPOINT_SNITCH", "GossipingPropertyFileSnitch")
                .WithEnvironment("CASSANDRA_NUM_TOKENS", "16")
                .WithEnvironment("CASSANDRA_DC", "nam")
                .WithEnvironment("CASSANDRA_RACK", "rack1")
                .WithEnvironment("MAX_HEAP_SIZE", "512M")
                .WithEnvironment("HEAP_NEWSIZE", "256M")
                .WithEnvironment("CQLSH_USER", scyllaUser)
                .WithEnvironment("CQLSH_PASSWORD", scyllaPassword)
                .WithEndpoint(port: cassandraEndpointPort, targetPort: 9042, name: "cql", scheme: "tcp")
                .PublishAsDockerComposeService((_, service) =>
                {
                    service.Networks = ["scylla"];
                    service.Healthcheck = new Healthcheck
                    {
                        Test = ["CMD-SHELL", "cqlsh -u \"$$CQLSH_USER\" -p \"$$CQLSH_PASSWORD\" -e 'describe cluster' || nodetool status | grep -q '^UN'"],
                        Interval = "15s",
                        Timeout = "10s",
                        Retries = 20,
                        StartPeriod = "30s"
                    };
                });

            if (includeApi && !includeScylla)
            {
                // Only attach the AppHost-level "scylla-health" check when Cassandra owns the
                // Ports:scylla endpoint. When Scylla is also included, Scylla owns it and the
                // Cassandra container relies on its own per-service compose healthcheck.
                cassandra.WithHealthCheck("scylla-health");
            }
            if (persistentContainers)
            {
                cassandra.WithVolume("cassandra_data", "/var/lib/cassandra");
                cassandra.WithLifetime(ContainerLifetime.Persistent);
            }

            cqlEndpointOwners.Add(cassandra);
        }

        // --- Database admin bootstrap ---
        // The bootstrapper's DatabaseInitPhase owns the admin/seed work that previously lived in
        // pg-bootstrap-auth and scylla-bootstrap-auth init containers. By the time the operator-
        // facing `docker compose up` runs, the app user has already been demoted to DML-only,
        // the `<user>_admin` role exists, and internal.secrets has been populated. The compose
        // file therefore contains only the app user's credentials - no init/admin password is
        // ever exposed via the compose graph.

        // --- Endpoint references (resolve to localhost:{hostPort} in dev, container:{targetPort} in compose) ---
        var pgEndpoint = msgDb.GetEndpoint("postgres");

        // --- Interfold API (from source for dev, or pre-built container image for self-hosting) ---
        // The self-hosting bootstrapper sets `Parameters:api-image` to a published image ref
        // (e.g. ghcr.io/interfold/api:1.2.3) so the published compose references the image
        // directly instead of trying to build the API csproj from the bootstrapper's deployment
        // directory (where the project file does not exist).
        if (includeApi)
        {
            void ConfigureApiCommon(IResourceBuilder<IResourceWithEnvironment> api)
            {
                api.WithEnvironment("OCTOCON_PERSISTENCE", "scylla-postgres")
                   .WithEnvironment("OCTOCON_SINGLE_SCYLLA_INSTANCE", isMultiScylla ? "false" : "true")
                   .WithEnvironment("OCTOCON_POSTGRES_CONNECTION",
                       ReferenceExpression.Create($"Host={pgEndpoint.Property(EndpointProperty.Host)};Port={pgEndpoint.Property(EndpointProperty.Port)};Database=octocon;Username={postgresUser};Password={postgresPassword}"))
                   .WithEnvironment("ENCRYPTION_PRIVATE_KEY", encryptionPrivateKey);
            }

            // Self-hosting only: the API container needs the bootstrapper-generated TLS material
            // for Kestrel HTTPS via a read-only bind mount:
            //   - /certs -> certs/  (root CA + leaf PFX from CertificatePhase)
            // The encryption pepper, JWT signing keys, deep-link HMAC secret, OAuth client
            // secrets, and leaf PFX password all live in `internal.secrets` exclusively.
            // SecretsBootstrapService patches the auth material (and refuses to start the API
            // if the pepper row is missing) and Program.cs runs a one-shot Npgsql query for
            // the leaf PFX password before Kestrel binds.
            static void ConfigureApiSelfHostEnv(IResourceBuilder<ContainerResource> api)
            {
                api.WithBindMount("../../certs", "/certs", isReadOnly: true)
                   // The published API container (built with `dotnet publish /t:PublishContainer`)
                   // defaults to listening on HTTP 8080. The Aspire compose graph below declares
                   // targetPort=5100/5101, so we override the SDK defaults to keep the two in
                   // sync. HTTPS terminates inside the container using the leaf PFX written by
                   // CertificatePhase - operators can still front this with a reverse proxy but
                   // direct HTTPS access works out of the box.
                   .WithEnvironment("ASPNETCORE_HTTP_PORTS", "5100")
                   .WithEnvironment("ASPNETCORE_HTTPS_PORTS", "5101")
                   // Kestrel default-endpoint cert path. Kestrel reads this from configuration
                   // (see https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel/endpoints#configure-https).
                   // The matching Password used to live in this env block too; it has moved to
                   // internal.secrets:certs:leaf_pfx_password and Program.cs loads it directly
                   // via a one-shot Npgsql query before Kestrel binds.
                   .WithEnvironment("ASPNETCORE_Kestrel__Certificates__Default__Path", "/certs/leaf.pfx");
            }

            var apiImageRef = builder.Configuration["Parameters:api-image"];
            if (!string.IsNullOrEmpty(apiImageRef))
            {
                // Self-hosting path: pre-built image reference, no csproj needed.
                var (imageName, imageTag) = SplitImageRef(apiImageRef);
                var apiContainer = builder.AddContainer("interfold-api", imageName, imageTag)
                    .WithHttpEndpoint(port: apiHttpPort, targetPort: 5100, name: "http")
                    .WithHttpsEndpoint(port: apiHttpsPort, targetPort: 5101, name: "https")
                    .WithHttpHealthCheck("/health/ready", endpointName: "http")
                    .WithExternalHttpEndpoints()
                    .WaitFor(msgDb)
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["scylla", "postgres", "api"];
                        service.Healthcheck = new Healthcheck
                        {
                            Test = ["CMD", "curl", "-f", "http://localhost:5100/health/ready"],
                            Interval = "15s",
                            Timeout = "5s",
                            Retries = 10,
                            StartPeriod = "20s"
                        };
                        // The admin/seed work runs in the bootstrapper (DatabaseInitPhase) before
                        // launch, so by the time docker compose up reaches the API the secrets
                        // table is already populated. We still gate on msg-db being healthy via
                        // depends_on so a freshly cleaned compose stack doesn't race to start the
                        // API before postgres opens its listening socket.
                        if (service.DependsOn.TryGetValue("msg-db", out var msgDbDep))
                            msgDbDep.Condition = "service_healthy";
                        // Gate API startup on scylla being CQL-ready, not merely on its container
                        // having entered the running state. Without this, the bootstrapper's
                        // `up` command (which doesn't run db-init and therefore doesn't pre-warm
                        // scylla itself) can race the API into scylla before the cluster has
                        // finished gossip-bootstrap, producing "connection refused on 9042" and
                        // a crash on the very first ScyllaMigrationService.StartingAsync call.
                        if (service.DependsOn.TryGetValue("scylla", out var scyllaDep))
                            scyllaDep.Condition = "service_healthy";
                        if (service.DependsOn.TryGetValue("cassandra", out var cassandraDep))
                            cassandraDep.Condition = "service_healthy";
                    });
                ConfigureApiCommon(apiContainer);
                ConfigureApiSelfHostEnv(apiContainer);
                foreach (var owner in cqlEndpointOwners)
                    apiContainer.WaitFor(owner);
            }
            else
            {
                var apiProject = builder.AddProject<Projects.Interfold_Api>("interfold-api")
                    .WithHttpEndpoint(port: apiHttpPort, targetPort: 5100, name: "http")
                    .WithHttpsEndpoint(port: apiHttpsPort, targetPort: 5101, name: "https")
                    .WithHttpHealthCheck("/health/ready", endpointName: "http")
                    .WithExternalHttpEndpoints()
                    .WaitFor(msgDb)
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["scylla", "postgres", "api"];
                        service.Healthcheck = new Healthcheck
                        {
                            Test = ["CMD", "curl", "-f", "http://localhost:5100/health/ready"],
                            Interval = "15s",
                            Timeout = "5s",
                            Retries = 10,
                            StartPeriod = "20s"
                        };
                        if (service.DependsOn.TryGetValue("msg-db", out var msgDbDep))
                            msgDbDep.Condition = "service_healthy";
                        if (service.DependsOn.TryGetValue("scylla", out var scyllaDep))
                            scyllaDep.Condition = "service_healthy";
                        if (service.DependsOn.TryGetValue("cassandra", out var cassandraDep))
                            cassandraDep.Condition = "service_healthy";
                    });
                ConfigureApiCommon(apiProject);
                foreach (var owner in cqlEndpointOwners)
                    apiProject.WaitFor(owner);
            }
        }

        // --- Octocon Web (pre-built container, optional) ---
        var includeWeb = !string.Equals(builder.Configuration["Parameters:include-web"], "false", StringComparison.OrdinalIgnoreCase);
        if (includeWeb)
        {
            builder.AddContainer("octocon-web", "ghcr.io/azyyyyyy/octocon-wasm", "latest")
                .WithContainerNetworkAlias("octocon-web")
                .WithHttpEndpoint(port: webHttpPort, targetPort: 80, name: "http")
                .WithHttpEndpoint(port: webHttpsPort, targetPort: 8080, name: "https")
                .WithHttpHealthCheck("/", endpointName: "http")
                .WithExternalHttpEndpoints()
                .PublishAsDockerComposeService((_, service) =>
                {
                    service.Networks = ["api"];
                    service.                    Healthcheck = new Healthcheck
                    {
                        Test = ["CMD", "curl", "-f", "http://localhost:80/"],
                        Interval = "15s",
                        Timeout = "5s",
                        Retries = 5,
                        StartPeriod = "10s"
                    };
                });
        }
    }

    /// <summary>
    /// Splits an image reference like <c>ghcr.io/foo/bar:1.2.3</c> or <c>interfold-api:test</c>
    /// into (image, tag). Tags only - SHA digests would need a different code path.
    /// </summary>
    private static (string Image, string Tag) SplitImageRef(string reference)
    {
        // Find the LAST colon that isn't inside the registry-port portion (e.g. localhost:5000/foo:tag).
        // The tag separator is the last colon after the last slash, since any colon before the last slash
        // belongs to the registry hostname.
        var lastSlash = reference.LastIndexOf('/');
        var lastColon = reference.LastIndexOf(':');
        if (lastColon > lastSlash && lastColon > 0)
        {
            return (reference[..lastColon], reference[(lastColon + 1)..]);
        }
        // No tag specified - default to "latest".
        return (reference, "latest");
    }
}
