using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.Docker.Resources.ComposeNodes;
using Aspire.Hosting.Docker.Resources.ServiceNodes;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using System.Net.Sockets;

// Deliberately *not* the assembly's matching `Interfold.AppHost` namespace - that conflicts with
// types generated by Aspire's AppHost SDK (notably `Projects.*` and a few SDK-private partial
// classes referencing the assembly name as a namespace). Use `Interfold.AppHostGraph` so the
// embedded bootstrapper can `using Interfold.AppHostGraph;` unambiguously.
namespace Interfold.AppHostGraph;

/// <summary>
/// Defines the Interfold distributed-application resource graph (Postgres, Scylla/Cassandra,
/// bootstrap-auth containers, the API, and the web container).
/// </summary>
/// <remarks>
/// Shared between two entry points:
/// <list type="bullet">
///   <item>The dev <c>Interfold.AppHost</c> executable (`aspire run` workflow).</item>
///   <item>The self-hosting <c>Interfold.Bootstrapper</c> executable, which pre-populates
///         <see cref="Microsoft.Extensions.Configuration.IConfiguration"/> with generated
///         secrets before calling <see cref="Configure"/> and then runs the publish flow
///         to emit a Docker Compose file.</item>
/// </list>
/// </remarks>
public static class InterfoldAppHost
{
    /// <summary>
    /// Registers the full Interfold resource graph on the supplied
    /// <see cref="IDistributedApplicationBuilder"/>. Does not call <c>Build()</c> or <c>Run()</c>.
    /// </summary>
    public static void Configure(IDistributedApplicationBuilder builder)
    {
        // --- Configurable host ports (must be declared before health checks reference them) ---
        int Port(string name, int fallback) => int.TryParse(builder.Configuration[$"Ports:{name}"], out var p) ? p : fallback;
        var postgresPort = Port("postgres", 4200);
        var scyllaPort = Port("scylla", 9042);
        // Cassandra has its own port slot so a single host can publish both Scylla and Cassandra
        // when the integration test SharedDbFixture asks for both. The legacy bootstrapper path
        // (only-cassandra-on-Ports:scylla) is preserved further down by falling back to
        // scyllaPort when Cassandra runs alone.
        var cassandraPort = Port("cassandra", 9043);
        var apiHttpPort = Port("api-http", 5000);
        var apiHttpsPort = Port("api-https", 5001);
        // Inside-the-container Kestrel ports for the API. These must match the EXPOSE/ARG
        // values baked into the published API image (see /Dockerfile, which defaults them to
        // 5100/5101 and accepts HTTP_PORT / HTTPS_PORT --build-arg overrides). When operators
        // rebuild the image with different ports, set Ports:api-container-http and
        // Ports:api-container-https to match - the targetPort, ASPNETCORE_*_PORTS env vars,
        // and the compose healthcheck URL all derive from these.
        var apiContainerHttpPort = Port("api-container-http", 5100);
        var apiContainerHttpsPort = Port("api-container-https", 5101);
        var webHttpPort = Port("web-http", 8080);
        var webHttpsPort = Port("web-https", 8081);

        // --- Optional feature flags (used by integration tests to disable API/web and use ephemeral containers) ---
        var includeApi = !string.Equals(builder.Configuration["Parameters:include-api"], "false", StringComparison.OrdinalIgnoreCase);
        var persistentContainers = !string.Equals(builder.Configuration["Parameters:persistent-containers"], "false", StringComparison.OrdinalIgnoreCase);

        // --- Per-resource toggles ---
        // The integration test SharedDbFixture flips these on/off based on which fixtures the
        // current test session actually requires (scanned via TUnit's TestSessionContext). Both
        // can be true at once so we run Scylla and Cassandra side-by-side under one Aspire host.
        // The bootstrapper's PublishPhase translates its operator-facing `databaseMode` enum
        // (single | multi | cassandra) into this same triple, so dev `aspire run`, the
        // bootstrapper, and the integration tests all drive the resource graph through the
        // same parameters. `scylla-topology` is independent of `include-cassandra` and only
        // affects the Scylla container layout when `include-scylla=true`.
        var includeScylla = ParseToggle(builder.Configuration["Parameters:include-scylla"], fallback: true);
        var includeCassandra = ParseToggle(builder.Configuration["Parameters:include-cassandra"], fallback: false);
        var scyllaTopology = builder.Configuration["Parameters:scylla-topology"] ?? "single";
        var isMultiScylla = string.Equals(scyllaTopology, "multi", StringComparison.OrdinalIgnoreCase);

        // CQL cluster identity baked into both backends. Cassandra picks it up via
        // CASSANDRA_CLUSTER_NAME (read by the official entrypoint and written into
        // cassandra.yaml); Scylla picks it up via the `--cluster-name` command-line flag
        // (alternative to the in-yaml setting and immune to image bake-time changes). Pure
        // metadata — surfaces in `SELECT cluster_name FROM system.local` and gossip, doesn't
        // appear in any query. Read here as a string (not an Aspire ParameterResource) so the
        // value flows into Scylla's WithArgs list without needing a callback shim, matching
        // the existing `includeScylla` / `scyllaTopology` config-read pattern. Defaults to
        // "InterfoldCluster" so dev `aspire run` works without operator config; the bootstrapper
        // overrides via `BootstrapConfig.ClusterName`.
        var clusterName = builder.Configuration["Parameters:cluster-name"] ?? "InterfoldCluster";

        // Postgres is unconditional in the dev `aspire run` workflow and the bootstrapper's
        // publish flow (the API depends on it), but the integration test
        // MultiNodeScyllaFixture flips this off so its multi-DC AppHost can share the
        // SharedDbFixture's existing msg-db container instead of starting a redundant
        // second Postgres instance. Defaulting to true preserves back-compat for every
        // caller that doesn't set the parameter.
        var includePostgres = ParseToggle(builder.Configuration["Parameters:include-postgres"], fallback: true);

        if (includeApi && !includePostgres)
        {
            // Guard against a misconfiguration that would silently land in a deployment with
            // an API that has nothing to talk to (the API's persistence path requires
            // Postgres for internal.secrets, hosted services, and migrations). Test fixtures
            // disable both toggles together.
            throw new InvalidOperationException(
                "Parameters:include-api=true requires Parameters:include-postgres=true (the API depends on msg-db).");
        }

        static bool ParseToggle(string? raw, bool fallback)
            => string.IsNullOrEmpty(raw)
                ? fallback
                : !string.Equals(raw, "false", StringComparison.OrdinalIgnoreCase);

        // --- Health checks for the Aspire dashboard (only when API is included) ---
        // In test mode (include-api=false), Aspire randomizes host ports, so TcpClient
        // health checks would fail. Without health checks, WaitFor() uses Running state.
        if (includeApi)
        {
            builder.Services.AddHealthChecks()
                .AddCheck("msg-db-health", () =>
                {
                    try
                    {
                        using var tcp = new TcpClient();
                        tcp.Connect("localhost", postgresPort);
                        return HealthCheckResult.Healthy();
                    }
                    catch { return HealthCheckResult.Unhealthy(); }
                })
                // `scylla-health` is the host-port TCP probe used by the Cassandra-only path
                // (Cassandra owns Ports:scylla when include-scylla=false). Scylla nodes get
                // their own per-node {name}-cql checks below — those are more accurate
                // (they probe inside the container, so they work for non-first multi-DC
                // nodes that don't have host ports) and supersede this one for the Scylla
                // path. We keep this registration for the Cassandra-only path only.
                .AddCheck("scylla-health", () =>
                {
                    try
                    {
                        using var tcp = new TcpClient();
                        tcp.Connect("localhost", scyllaPort);
                        return HealthCheckResult.Healthy();
                    }
                    catch { return HealthCheckResult.Unhealthy(); }
                });
        }

        // --- Per-node Scylla CQL readiness gate (always-on, regardless of include-api) ---
        // Each Scylla container gets a {name}-cql IHealthCheck that shells `docker ps` to
        // resolve the runtime container name, then `docker exec <name> sh -c
        // "<cqlsh-or-nodetool>"` inside the container. Because every node carries a
        // HealthCheckAnnotation, the WaitFor(previousNode) chain in the Scylla loop below
        // automatically upgrades from "wait for Running" to "wait for Healthy", which
        // serialises the cluster join sequence — without this, all 7 multi-DC nodes hit the
        // Raft topology coordinator simultaneously and the loser gets banned (Scylla 2026.1
        // only admits one joiner at a time).
        //
        // We resolve the container name on every probe by `docker ps`-filter rather than via a
        // BackgroundService watching ResourceNotificationService — empirically, custom
        // hosted services don't fire reliably under Aspire.Hosting.Testing's in-process host
        // when multiple AspireFixtures coexist in one test session (only the first fixture's
        // BackgroundService actually ran in artifacts/multinode-stagger-debug.log). Polling
        // docker for the runtime name keeps the check stateless and works identically for
        // `aspire run` and the testing host.
        if (includeScylla)
        {
            // We mirror the region-list resolution done deeper in the AppHost (search for
            // `isMultiScylla`) so the health-check names line up exactly with the resource
            // names added later. Keeping the resolution inline here (instead of hoisting it
            // out of the Scylla block) localises the change and avoids accidentally moving
            // unrelated logic.
            string[] regionsForChecks = isMultiScylla
                ? ["nam", "eur", "sam", "sas", "eas", "ocn", "gdpr"]
                : ["nam"];

            var hcBuilder = builder.Services.AddHealthChecks();
            foreach (var region in regionsForChecks)
            {
                var resourceName = regionsForChecks.Length > 1 ? $"scylla-{region}" : "scylla";
                hcBuilder.AddAsyncCheck($"{resourceName}-cql", async ct =>
                    await DockerExecCqlProbe.RunAsync(resourceName, ct).ConfigureAwait(false));
            }
        }

        // --- Docker Compose publish target with network isolation ---
        // The bootstrapper sets `Parameters:include-dashboard=false` because the Aspire dashboard
        // resource pulls `mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest` at compose-up
        // time, which is not appropriate for self-hosted production stacks (network egress to MCR,
        // nightly image churn). The dev `aspire run` workflow keeps the dashboard.
        var includeDashboard = !string.Equals(builder.Configuration["Parameters:include-dashboard"], "false", StringComparison.OrdinalIgnoreCase);
        builder.AddDockerComposeEnvironment("docker-compose")
            .WithDashboard(includeDashboard)
            .ConfigureComposeFile(compose =>
            {
                compose.AddNetwork(new Network { Name = "scylla", Driver = "bridge" });
                compose.AddNetwork(new Network { Name = "postgres", Driver = "bridge" });
                compose.AddNetwork(new Network { Name = "api", Driver = "bridge" });

                // Dashboard needs to be reachable by API for OTLP telemetry
                if (compose.Services.TryGetValue("docker-compose-dashboard", out var dashboard))
                {
                    dashboard.Networks.Add("api");
                }
            });

        // --- Parameters (set via user-secrets or environment variables) ---
        var postgresUser = builder.AddParameter("postgres-user");
        var postgresPassword = builder.AddParameter("postgres-password", secret: true);
        // Postgres application database name. Defaults to `interfold` so dev `aspire run`
        // works without any extra config; the bootstrapper overrides this from
        // `BootstrapConfig.PostgresDatabase` in publish mode (via `Parameters:postgres-db`),
        // and the resulting value flows into both the API's connection string below and
        // DatabaseInitPhase's CREATE DATABASE call via the matching seed option. Not a
        // secret — it ends up in compose YAML / .env as plain text.
        var postgresDb = builder.AddParameter("postgres-db", "interfold", publishValueAsDefault: true);
        // Transient init credential. POSTGRES_USER on the msg-db service is hard-coded to
        // "db_init" - a disposable cluster-owner that the bootstrapper's DatabaseInitPhase uses
        // exactly once to create the real app + admin roles, then ALTERs to a fresh random
        // password we don't persist anywhere. The .env value sitting in the operator's
        // deployment dir is intentionally stale by the time the API starts.
        //
        // Default value: GenerateParameterDefault produces a random 24-char password on first
        // run and persists it to user-secrets (persist: true) so `aspire run` and the
        // TUnit.Aspire integration tests can spin up the resource graph without the developer
        // pre-seeding `Parameters:postgres-init-password`. In publish mode the bootstrapper's
        // PublishPhase.BuildEnvReplacements overrides this value with the one in secrets.json
        // before the .env file is materialised, so the generated default never leaks into a
        // production deployment.
        var postgresInitPassword = builder.AddParameter("postgres-init-password",
            new GenerateParameterDefault { MinLength = 24 }, secret: true, persist: true);
        var scyllaUser = builder.AddParameter("scylla-user");
        var scyllaPassword = builder.AddParameter("scylla-password", secret: true);
        // The matching `<user>_admin` role is created by the bootstrapper's DatabaseInitPhase with
        // a freshly generated password that lives only inside internal.secrets - it is never
        // surfaced as an AppHost parameter or compose env var.
        var encryptionPrivateKey = builder.AddParameter("encryption-private-key", secret: true);
        // The encryption pepper moved into internal.secrets:encryption:pepper.
        // SecretsBootstrapService patches AuthenticationConfiguration.EncryptionPepper at
        // startup and refuses to boot the API if the row is missing.
        // The leaf PFX password moved into internal.secrets:certs:leaf_pfx_password.
        // Program.cs runs a one-shot Npgsql query to load it into the Kestrel default-cert
        // configuration before the HTTPS endpoint binds, so the AppHost no longer needs a
        // parameter for it.

        // Public OAuth client IDs - paired with the per-provider client secrets that live in
        // internal.secrets. Sourced from BootstrapConfig.OAuth.*ClientId via the
        // Parameters:*-oauth-client-id IConfiguration override the bootstrapper sets in
        // PublishPhase. Declared as non-secret with `publishValueAsDefault: true` and an
        // empty default so:
        //   - the dev `aspire run` workflow does NOT fail when the operator hasn't set any
        //     OAuth credentials (the project path reads the matching OCTOCON_*_OAUTH_CLIENT_ID
        //     directly from launchSettings.json / user-secrets and overrides whatever Aspire
        //     pushed in via ConfigureApiSelfHostEnv, since that helper only attaches them to
        //     the container path further down);
        //   - the bootstrapper publish path surfaces them as plain `.env` entries that the
        //     `BuildEnvReplacements` step fills with the operator-supplied values.
        // The scheme is only registered when the matching client ID is non-empty (see
        // OAuthChallengeServiceCollectionExtensions); leaving the ID blank for a provider
        // disables that provider, which is the intended "I'm not using this one" behaviour.
        var googleOAuthClientId = builder.AddParameter("google-oauth-client-id", "", publishValueAsDefault: true);
        var discordOAuthClientId = builder.AddParameter("discord-oauth-client-id", "", publishValueAsDefault: true);
        var appleOAuthClientId = builder.AddParameter("apple-oauth-client-id", "", publishValueAsDefault: true);

        // --- API runtime parameters (non-secret, set by the bootstrapper) ---
        // These five plain-text values used to be operator env vars on `docker compose up` (or
        // missing entirely — OCTOCON_JWT_AUDIENCE was documented but never bound). The bootstrapper
        // now manages them end-to-end: ConfigPhase prompts for each value (with derived defaults
        // sourced from BootstrapConfig.Deployment) and ConfigureApiSelfHostEnv below pipes them
        // onto the API container as OCTOCON_* env vars. Empty defaults are intentional — Validate
        // refuses to emit a bootstrap without them, and a non-empty operator-supplied value always
        // wins over the bootstrapper's derived default.
        var scyllaKeyspace = builder.AddParameter("scylla-keyspace", "nam", publishValueAsDefault: true);
        var oauthCallbackBaseUrl = builder.AddParameter("oauth-callback-base-url", "", publishValueAsDefault: true);
        var jwtAuthority = builder.AddParameter("jwt-authority", "", publishValueAsDefault: true);
        var jwtAudience = builder.AddParameter("jwt-audience", "octocon", publishValueAsDefault: true);
        var corsAllowedOrigins = builder.AddParameter("cors-allowed-origins", "", publishValueAsDefault: true);

        // --- Operator tuning parameters (non-secret, set by the bootstrapper) ---
        // Mirror the optional knobs on PersistenceConfiguration / ClusterConfiguration /
        // StorageConfiguration / ObservabilityConfiguration / SocketConfiguration. Every
        // parameter declares the API's compile-time fallback as the default so leaving
        // BootstrapConfig at its defaults reproduces today's "env var unset" behaviour
        // 1:1; the bootstrapper writes the operator-supplied value through PublishPhase
        // when they deviate. The two nullable / disabled-by-default fields (avatar paths,
        // OTLP endpoint, socket threshold) declare an empty default — ApplyStorage /
        // ApplyObservability normalise empty → null so the API's not-configured paths
        // still trigger.
        var nodeGroup = builder.AddParameter("node-group", "auxiliary", publishValueAsDefault: true);
        var avatarStorageRoot = builder.AddParameter("avatar-storage-root", "", publishValueAsDefault: true);
        var avatarPublicBase = builder.AddParameter("avatar-public-base", "", publishValueAsDefault: true);
        var otlpEndpoint = builder.AddParameter("otlp-endpoint", "", publishValueAsDefault: true);
        var socketBatchBytesThreshold = builder.AddParameter("socket-batch-bytes-threshold", "", publishValueAsDefault: true);
        var dbRetryAttempts = builder.AddParameter("db-retry-attempts", "3", publishValueAsDefault: true);
        var dbRetryInitialDelayMs = builder.AddParameter("db-retry-initial-delay-ms", "100", publishValueAsDefault: true);
        var dbRetryMaxDelayMs = builder.AddParameter("db-retry-max-delay-ms", "1500", publishValueAsDefault: true);
        var hydrationMaxConcurrency = builder.AddParameter("hydration-max-concurrency", "8", publishValueAsDefault: true);

        // --- Reject well-known default passwords at startup (dev mode only; compose relies on shell guard) ---
        // Each backend's check is gated on the matching `include-*` toggle so a caller that
        // explicitly opted out of standing up that backend (e.g. integration tests like
        // MultiNodeScyllaFixture run with include-postgres=false) doesn't have to invent
        // placeholder credentials for resources the AppHost is about to skip below anyway.
        // Defaults keep every toggle true, so the dev `aspire run` workflow still gets the
        // full safety net.
        if (!builder.ExecutionContext.IsPublishMode)
        {
            if (includeScylla)
            {
                var scyllaPasswordValue = builder.Configuration["Parameters:scylla-password"];
                if (string.IsNullOrEmpty(scyllaPasswordValue) || scyllaPasswordValue == "cassandra")
                {
                    throw new InvalidOperationException(
                        "SCYLLA_PASSWORD must be set to a non-default value. " +
                        "The well-known default 'cassandra' is not allowed.\n" +
                        "Fix: dotnet user-secrets set \"Parameters:scylla-password\" \"<your-secure-password>\" " +
                        "--project csharp/Interfold.AppHost");
                }

                var scyllaUserValue = builder.Configuration["Parameters:scylla-user"];
                if (string.IsNullOrEmpty(scyllaUserValue) || scyllaUserValue == "cassandra")
                {
                    throw new InvalidOperationException(
                        "SCYLLA_USER must be set to a non-default value. " +
                        "The well-known default 'cassandra' is not allowed.\n" +
                        "Fix: dotnet user-secrets set \"Parameters:scylla-user\" \"<your-username>\" " +
                        "--project csharp/Interfold.AppHost");
                }
            }

            if (includePostgres)
            {
                var postgresPasswordValue = builder.Configuration["Parameters:postgres-password"];
                if (string.IsNullOrEmpty(postgresPasswordValue) || postgresPasswordValue == "postgres")
                {
                    throw new InvalidOperationException(
                        "POSTGRES_PASSWORD must be set to a non-default value. " +
                        "The well-known default 'postgres' is not allowed.\n" +
                        "Fix: dotnet user-secrets set \"Parameters:postgres-password\" \"<your-secure-password>\" " +
                        "--project csharp/Interfold.AppHost");
                }

                var postgresUserValue = builder.Configuration["Parameters:postgres-user"];
                if (string.IsNullOrEmpty(postgresUserValue) || postgresUserValue == "postgres")
                {
                    throw new InvalidOperationException(
                        "POSTGRES_USER must be set to a non-default value. " +
                        "The well-known default 'postgres' is not allowed.\n" +
                        "Fix: dotnet user-secrets set \"Parameters:postgres-user\" \"<your-username>\" " +
                        "--project csharp/Interfold.AppHost");
                }
            }
        }

        // --- PostgreSQL (TimescaleDB) ---
        // Skipped entirely when `Parameters:include-postgres=false` (the multi-DC integration
        // test fixture sets this so it can share SharedDbFixture's existing msg-db rather
        // than starting a redundant Postgres). The earlier guard (`includeApi && !includePostgres`)
        // ensures every includeApi codepath below this point still has a non-null `msgDb` to
        // wire up.
        //
        // First-boot pattern (least-privilege):
        //   - `POSTGRES_USER=db_init`: postgres creates db_init as the bootstrap superuser
        //     (OID 10). We can't ever demote that role per postgres' own hard-coded restriction
        //     (commands/user.c::AlterRole), so we use a disposable name for it.
        //   - `POSTGRES_PASSWORD=${POSTGRES_INIT_PASSWORD}`: the transient init credential.
        //     DatabaseInitPhase consumes it once to mint the real app + admin roles, then
        //     scrambles db_init's password to a fresh random value the bootstrapper does not
        //     persist. The compose .env value is therefore stale by the time the API starts.
        //   - No `POSTGRES_DB`: DatabaseInitPhase creates the application database (named via
        //     `Parameters:postgres-db`, default `interfold`) owned by the admin role, not by
        //     db_init - keeps DDL gating consistent.
        //
        // The interfold-api connection string below references `${POSTGRES_USER}` /
        // `${POSTGRES_PASSWORD}` which resolve to the *app* user (interfold), not db_init. So the
        // only PostgreSQL connection string in the compose graph is the app's.
        IResourceBuilder<ContainerResource>? msgDb = null;
        if (includePostgres)
        {
            msgDb = builder.AddContainer("msg-db", "timescale/timescaledb", "latest-pg18")
                .WithContainerNetworkAlias("msg-db")
                .WithEnvironment("POSTGRES_USER", "db_init")
                .WithEnvironment("POSTGRES_PASSWORD", postgresInitPassword)
                .WithEnvironment("PGDATA", "/var/lib/postgresql/data/pgdata")
                // initdb's default --auth-host is `trust`, which produces `host all all 127.0.0.1/32 trust`
                // in pg_hba.conf BEFORE the entrypoint appends `host all all all scram-sha-256`. With
                // first-match-wins ordering, TCP loopback connections (e.g. `psql -h 127.0.0.1` from
                // inside the container) silently bypass the password check — defeating the bootstrapper's
                // db_init password scramble. Forcing scram-sha-256 for every host entry closes that
                // loophole and matches the security posture the rest of the stack assumes.
                //
                // Unix socket connections still use `local all all trust`, which is what the bootstrapper's
                // DatabaseInitPhase relies on (it connects as db_init via the socket to mint the app +
                // admin roles before the password is scrambled).
                .WithEnvironment("POSTGRES_INITDB_ARGS", "--auth-host=scram-sha-256")
                // Bump pg_ctl's wait timeout from the 60s default. The postgres image entrypoint
                // does `pg_ctl -m fast -w stop` after the timescaledb-tune init script runs, then
                // re-execs postgres in normal mode. On slow Docker-in-Docker disks the shutdown
                // checkpoint can take well past 60s, which makes the entrypoint exit with
                // "pg_ctl: server does not shut down" and the container die before the bootstrapper's
                // WaitForPostgresAsync ever sees normal mode. 300s gives us comfortable headroom.
                .WithEnvironment("PGCTLTIMEOUT", "300")
                // timescaledb-tune (the image's 001_timescaledb_tune.sh init script) reads
                // /sys/fs/cgroup/memory.max to size shared_buffers. Self-hosting hosts running on
                // Docker Desktop / cgroup-v2-restricted environments may not expose that file, in
                // which case the tune script panics and the container exits during init. Setting
                // TS_TUNE_MEMORY + TS_TUNE_NUM_CPUS bypasses auto-detection with safe conservative
                // defaults; operators on bigger boxes can override these env vars in a
                // docker-compose.override.yaml without re-running the bootstrapper.
                .WithEnvironment("TS_TUNE_MEMORY", "1GB")
                .WithEnvironment("TS_TUNE_NUM_CPUS", "2")
                .WithEndpoint(port: postgresPort, targetPort: 5432, name: "postgres", scheme: "tcp")
                .PublishAsDockerComposeService((_, service) =>
                {
                    service.Networks = ["postgres"];
                    service.Healthcheck = new Healthcheck
                    {
                        Test = ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d postgres"],
                        Interval = "10s",
                        Timeout = "5s",
                        Retries = 10,
                        StartPeriod = "15s"
                    };
                });
            if (includeApi)
                msgDb.WithHealthCheck("msg-db-health");
            if (persistentContainers)
            {
                msgDb.WithVolume("msg_pgdata", "/var/lib/postgresql/data");
                msgDb.WithLifetime(ContainerLifetime.Persistent);
            }
        }

        // --- ScyllaDB / Cassandra (independent toggles, can both be on at once) ---
        // Resources the API container needs to wait on before starting. Populated below as each
        // included CQL backend stands up. When both are on, the API depends on both.
        var cqlEndpointOwners = new List<IResourceBuilder<ContainerResource>>();

        if (includeScylla)
        {
            // --- ScyllaDB nodes (single or multi based on scylla-topology) ---
            string[] regions = isMultiScylla
                ? ["nam", "eur", "sam", "sas", "eas", "ocn", "gdpr"]
                : ["nam"];

            IResourceBuilder<ContainerResource>? previousNode = null;

            foreach (var region in regions)
            {
                var name = regions.Length > 1 ? $"scylla-{region}" : "scylla";
                var seeds = previousNode is null ? $"--seeds={name}" : $"--seeds=scylla-{regions[0]},scylla-{regions[1]}";

                // Belt-and-braces for the multi-DC topology: even with the per-node CQL
                // health-check chain serialising joins below, Scylla 2026.1's Raft topology
                // coordinator benefits from extra settle time between joiners. Default
                // ring-delay-ms is 30 s; bumping to 60 s for multi-DC widens the window
                // before a joining node concludes ring metadata is settled. Cheap insurance,
                // no measurable effect on single-node.
                var nodeArgs = new List<string>
                {
                    seeds, "--smp", "1", "--memory", "750M", "--overprovisioned", "1",
                    "--developer-mode", "1", "--authenticator", "PasswordAuthenticator",
                    "--authorizer", "CassandraAuthorizer",
                    "--endpoint-snitch", "GossipingPropertyFileSnitch",
                    "--api-address", "0.0.0.0", "--broadcast-address", name,
                    // Operator-tunable cluster identity (default "InterfoldCluster"); without
                    // this Scylla falls back to its built-in "Test Cluster" name, which is
                    // both unbranded and easily confused with a real Scylla test image.
                    "--cluster-name", clusterName,
                };
                if (isMultiScylla)
                {
                    nodeArgs.Add("--ring-delay-ms");
                    nodeArgs.Add("60000");
                }

                var node = builder.AddContainer(name, "scylladb/scylla", "2026.1")
                    .WithContainerNetworkAlias(name)
                    .WithArgs([.. nodeArgs])
                    .WithBindMount($"../../db/scylla/cassandra-rackdc.{region}.properties", "/etc/scylla/cassandra-rackdc.properties", isReadOnly: true)
                    .WithEnvironment("CQLSH_USER", scyllaUser)
                    .WithEnvironment("CQLSH_PASSWORD", scyllaPassword)
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["scylla"];
                        // `nodetool status` returning UN means gossip-bootstrap is done, but the
                        // CQL listener can come up several seconds later (we've observed gaps of
                        // 60–90s on slow DinD hosts between NORMAL mode and "Starting listening
                        // for CQL clients on ...:9042"). Probe the actual CQL endpoint with the
                        // app role so depends_on:service_healthy really means "CQL is reachable
                        // as the app user". Pre-bootstrap (before DatabaseInitPhase has minted
                        // the role) this probe fails, but the API doesn't depend on this
                        // healthcheck during that window — the bootstrapper uses its own
                        // WaitForScyllaAsync against the default cassandra session instead.
                        //
                        // The doubled `$$` is intentional: docker-compose interpolates `${VAR}`
                        // and `$VAR` at YAML-parse time using host-shell env vars, which is NOT
                        // what we want for healthcheck commands. `$$VAR` escapes to a literal
                        // `$VAR` that the container's `/bin/sh -c` will expand against the
                        // container's own env (where CQLSH_USER / CQLSH_PASSWORD are set).
                        service.Healthcheck = new Healthcheck
                        {
                            Test = ["CMD-SHELL",
                                "cqlsh -u \"$$CQLSH_USER\" -p \"$$CQLSH_PASSWORD\" -e 'DESCRIBE CLUSTER' >/dev/null 2>&1"],
                            Interval = "15s",
                            Timeout = "10s",
                            Retries = 20,
                            StartPeriod = "30s"
                        };
                    });

                if (persistentContainers)
                {
                    node.WithVolume(regions.Length > 1 ? $"scylla_{region}_data" : "scylla_data", "/var/lib/scylla");
                    node.WithLifetime(ContainerLifetime.Persistent);
                }

                // Attach the per-node CQL readiness gate registered earlier. Carrying a
                // HealthCheckAnnotation flips the semantics of WaitFor(previousNode) below
                // from "wait for Running" (~container started) to "wait for Healthy" (CQL
                // accepting traffic), which serialises the multi-DC join sequence and avoids
                // the Raft topology coordinator banning concurrent joiners.
                node.WithHealthCheck($"{name}-cql");

                if (previousNode is null)
                {
                    node.WithEndpoint(port: scyllaPort, targetPort: 9042, name: "cql", scheme: "tcp");
                    cqlEndpointOwners.Add(node);
                }
                else
                {
                    node.WaitFor(previousNode);
                }

                previousNode = node;
            }
        }

        if (includeCassandra)
        {
            // --- Cassandra 5 ---
            // Built from db/cassandra/Dockerfile (FROM cassandra:5), which bakes the
            // cassandra.yaml overrides we need (materialized_views_enabled,
            // PasswordAuthenticator, CassandraAuthorizer) into the image at build time. That
            // removes the need for a runtime wrapper script and avoids the bind-mount/chown
            // pitfalls that previously broke Cassandra on GHA. Datacenter/rack are set via env
            // vars; the official entrypoint writes them into cassandra-rackdc.properties using
            // an in-place rewrite that does not rename.
            //
            // Endpoint port: when running alone (legacy bootstrapper "cassandra mode") the
            // operator's compose .env writes `Ports:scylla=9042` and Cassandra binds there for
            // back-compat. When running alongside Scylla under the integration test
            // SharedDbFixture, both toggles are on and Cassandra uses its own `Ports:cassandra`
            // slot (default 9043) so the two CQL listeners don't collide.
            var cassandraEndpointPort = includeScylla ? cassandraPort : scyllaPort;

            var cassandra = builder.AddDockerfile("cassandra", "../../db/cassandra")
                .WithContainerNetworkAlias("cassandra")
                .WithEnvironment("CASSANDRA_CLUSTER_NAME", clusterName)
                .WithEnvironment("CASSANDRA_LISTEN_ADDRESS", "cassandra")
                .WithEnvironment("CASSANDRA_BROADCAST_ADDRESS", "cassandra")
                .WithEnvironment("CASSANDRA_BROADCAST_RPC_ADDRESS", "cassandra")
                .WithEnvironment("CASSANDRA_RPC_ADDRESS", "0.0.0.0")
                .WithEnvironment("CASSANDRA_ENDPOINT_SNITCH", "GossipingPropertyFileSnitch")
                .WithEnvironment("CASSANDRA_NUM_TOKENS", "16")
                .WithEnvironment("CASSANDRA_DC", "nam")
                .WithEnvironment("CASSANDRA_RACK", "rack1")
                .WithEnvironment("MAX_HEAP_SIZE", "512M")
                .WithEnvironment("HEAP_NEWSIZE", "256M")
                .WithEnvironment("CQLSH_USER", scyllaUser)
                .WithEnvironment("CQLSH_PASSWORD", scyllaPassword)
                .WithEndpoint(port: cassandraEndpointPort, targetPort: 9042, name: "cql", scheme: "tcp")
                .PublishAsDockerComposeService((_, service) =>
                {
                    service.Networks = ["scylla"];
                    service.Healthcheck = new Healthcheck
                    {
                        Test = ["CMD-SHELL", "cqlsh -u \"$$CQLSH_USER\" -p \"$$CQLSH_PASSWORD\" -e 'describe cluster' || nodetool status | grep -q '^UN'"],
                        Interval = "15s",
                        Timeout = "10s",
                        Retries = 20,
                        StartPeriod = "30s"
                    };
                });

            if (includeApi && !includeScylla)
            {
                // Only attach the AppHost-level "scylla-health" check when Cassandra owns the
                // Ports:scylla endpoint. When Scylla is also included, Scylla owns it and the
                // Cassandra container relies on its own per-service compose healthcheck.
                cassandra.WithHealthCheck("scylla-health");
            }
            if (persistentContainers)
            {
                cassandra.WithVolume("cassandra_data", "/var/lib/cassandra");
                cassandra.WithLifetime(ContainerLifetime.Persistent);
            }

            cqlEndpointOwners.Add(cassandra);
        }

        // --- Database admin bootstrap ---
        // The bootstrapper's DatabaseInitPhase owns the admin/seed work that previously lived in
        // pg-bootstrap-auth and scylla-bootstrap-auth init containers. By the time the operator-
        // facing `docker compose up` runs, the app user has already been demoted to DML-only,
        // the `<user>_admin` role exists, and internal.secrets has been populated. The compose
        // file therefore contains only the app user's credentials - no init/admin password is
        // ever exposed via the compose graph.

        // --- Interfold API (from source for dev, or pre-built container image for self-hosting) ---
        // The self-hosting bootstrapper sets `Parameters:api-image` to a published image ref
        // (e.g. ghcr.io/azyyyyyy/interfold-api:1.2.3) so the published compose references the image
        // directly instead of trying to build the API csproj from the bootstrapper's deployment
        // directory (where the project file does not exist).
        if (includeApi)
        {
            // The earlier guard (`includeApi && !includePostgres` -> throw) means msgDb is
            // guaranteed non-null on this branch.
            var msgDbResource = msgDb!;
            var pgEndpoint = msgDbResource.GetEndpoint("postgres");

            void ConfigureApiCommon(IResourceBuilder<IResourceWithEnvironment> api)
            {
                api.WithEnvironment("OCTOCON_PERSISTENCE", "scylla-postgres")
                   .WithEnvironment("OCTOCON_SINGLE_SCYLLA_INSTANCE", isMultiScylla ? "false" : "true")
                   .WithEnvironment("OCTOCON_POSTGRES_CONNECTION",
                       ReferenceExpression.Create($"Host={pgEndpoint.Property(EndpointProperty.Host)};Port={pgEndpoint.Property(EndpointProperty.Port)};Database={postgresDb};Username={postgresUser};Password={postgresPassword}"))
                   .WithEnvironment("ENCRYPTION_PRIVATE_KEY", encryptionPrivateKey);
            }

            // Self-hosting only: the API container needs the bootstrapper-generated TLS material
            // for Kestrel HTTPS via a read-only bind mount:
            //   - /certs -> certs/  (root CA + leaf PFX from CertificatePhase)
            // The encryption pepper, JWT signing keys, deep-link HMAC secret, OAuth client
            // secrets, and leaf PFX password all live in `internal.secrets` exclusively.
            // SecretsBootstrapService patches the auth material (and refuses to start the API
            // if the pepper row is missing) and Program.cs runs a one-shot Npgsql query for
            // the leaf PFX password before Kestrel binds.
            //
            // Note: this captures `apiContainerHttpPort`/`apiContainerHttpsPort` from the
            // enclosing scope so it cannot be `static`.
            void ConfigureApiSelfHostEnv(IResourceBuilder<ContainerResource> api)
            {
                api.WithBindMount("../../certs", "/certs", isReadOnly: true)
                   // The published API container (built with `dotnet publish /t:PublishContainer`)
                   // defaults to listening on HTTP 8080. The Aspire compose graph below declares
                   // targetPort=apiContainerHttpPort/apiContainerHttpsPort, so we override the SDK
                   // defaults to keep the two in sync. HTTPS terminates inside the container using
                   // the leaf PFX written by CertificatePhase - operators can still front this with
                   // a reverse proxy but direct HTTPS access works out of the box.
                   .WithEnvironment("ASPNETCORE_HTTP_PORTS", apiContainerHttpPort.ToString())
                   .WithEnvironment("ASPNETCORE_HTTPS_PORTS", apiContainerHttpsPort.ToString())
                   // Kestrel default-endpoint cert path. Kestrel reads this from configuration
                   // (see https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel/endpoints#configure-https).
                   // The matching Password used to live in this env block too; it has moved to
                   // internal.secrets:certs:leaf_pfx_password and Program.cs loads it directly
                   // via a one-shot Npgsql query before Kestrel binds.
                   .WithEnvironment("ASPNETCORE_Kestrel__Certificates__Default__Path", "/certs/leaf.pfx")
                   // OAuth client IDs are public per-provider identifiers that get rendered into
                   // each scheme's authorize-redirect URL. Attached on the container path only so
                   // the dev `aspire run` workflow keeps reading them from launchSettings.json /
                   // user-secrets (the project path inherits from that, not from these
                   // parameters). Per-provider empty values are explicitly allowed - leaving a
                   // provider's ID empty causes the API's scheme registrar to skip that
                   // provider entirely.
                   .WithEnvironment("OCTOCON_GOOGLE_OAUTH_CLIENT_ID", googleOAuthClientId)
                   .WithEnvironment("OCTOCON_DISCORD_OAUTH_CLIENT_ID", discordOAuthClientId)
                   .WithEnvironment("OCTOCON_APPLE_OAUTH_CLIENT_ID", appleOAuthClientId)
                   // API runtime config sourced from BootstrapConfig (see ConfigPhase.PromptForConfig
                   // and BootstrapConfig.ApiRuntime). Attached only to the container path so the
                   // dev `aspire run` workflow keeps reading these from launchSettings.json /
                   // user-secrets like every other API env var.
                   //   * OCTOCON_SCYLLA_KEYSPACE — gotcha #1 in docs/configuration.md; without
                   //     this set the API defaults to 'nam' which is wrong for any non-NAM
                   //     regional stack.
                   //   * OCTOCON_AUTH_CALLBACK_BASE_URL — base URL the OAuth callbacks redirect
                   //     to. Without this, the OAuth handshake completes with a 400.
                   //   * OCTOCON_JWT_AUTHORITY / OCTOCON_JWT_AUDIENCE — JWT iss/aud claims;
                   //     bootstrapper-managed so the operator's canonical API URL flows through.
                   //   * OCTOCON_CORS_ALLOWED_ORIGINS — comma-separated allow-list. Empty falls
                   //     back to "allow any origin" in Program.cs, which is a production
                   //     foot-gun; the bootstrapper derives a default from Domains.
                   .WithEnvironment("OCTOCON_SCYLLA_KEYSPACE", scyllaKeyspace)
                   .WithEnvironment("OCTOCON_AUTH_CALLBACK_BASE_URL", oauthCallbackBaseUrl)
                   .WithEnvironment("OCTOCON_JWT_AUTHORITY", jwtAuthority)
                   .WithEnvironment("OCTOCON_JWT_AUDIENCE", jwtAudience)
                   .WithEnvironment("OCTOCON_CORS_ALLOWED_ORIGINS", corsAllowedOrigins)
                   // Operator tuning vars sourced from BootstrapConfig's persistence /
                   // cluster / storage / observability / socket sections. Each carries
                   // the API's compile-time default so a fresh bootstrap with no operator
                   // input still produces identical container behaviour to a pre-rollout
                   // stack that never set these vars. The three "disabled when empty"
                   // fields (avatars, OTLP, socket threshold) round-trip through
                   // ApplyStorage / ApplyObservability / TryParseInt, which normalise
                   // empty → null so the API's not-configured branches still fire.
                   .WithEnvironment("OCTOCON_NODE_GROUP", nodeGroup)
                   .WithEnvironment("OCTOCON_AVATAR_STORAGE_ROOT", avatarStorageRoot)
                   .WithEnvironment("OCTOCON_AVATAR_PUBLIC_BASE", avatarPublicBase)
                   .WithEnvironment("OCTOCON_OTLP_ENDPOINT", otlpEndpoint)
                   .WithEnvironment("OCTOCON_SOCKET_BATCH_BYTES_THRESHOLD", socketBatchBytesThreshold)
                   .WithEnvironment("OCTOCON_DB_RETRY_ATTEMPTS", dbRetryAttempts)
                   .WithEnvironment("OCTOCON_DB_RETRY_INITIAL_DELAY_MS", dbRetryInitialDelayMs)
                   .WithEnvironment("OCTOCON_DB_RETRY_MAX_DELAY_MS", dbRetryMaxDelayMs)
                   .WithEnvironment("OCTOCON_HYDRATION_MAX_CONCURRENCY", hydrationMaxConcurrency);
            }

            var apiImageRef = builder.Configuration["Parameters:api-image"];
            if (!string.IsNullOrEmpty(apiImageRef))
            {
                // Self-hosting path: pre-built image reference, no csproj needed.
                var (imageName, imageTag) = SplitImageRef(apiImageRef);
                var apiContainer = builder.AddContainer("interfold-api", imageName, imageTag)
                    .WithHttpEndpoint(port: apiHttpPort, targetPort: apiContainerHttpPort, name: "http")
                    .WithHttpsEndpoint(port: apiHttpsPort, targetPort: apiContainerHttpsPort, name: "https")
                    .WithHttpHealthCheck("/health/ready", endpointName: "http")
                    .WithExternalHttpEndpoints()
                    .WaitFor(msgDbResource)
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["scylla", "postgres", "api"];
                        service.Healthcheck = new Healthcheck
                        {
                            Test = ["CMD", "curl", "-f", $"http://localhost:{apiContainerHttpPort}/health/ready"],
                            Interval = "15s",
                            Timeout = "5s",
                            Retries = 10,
                            StartPeriod = "20s"
                        };
                        // The admin/seed work runs in the bootstrapper (DatabaseInitPhase) before
                        // launch, so by the time docker compose up reaches the API the secrets
                        // table is already populated. We still gate on msg-db being healthy via
                        // depends_on so a freshly cleaned compose stack doesn't race to start the
                        // API before postgres opens its listening socket.
                        if (service.DependsOn.TryGetValue("msg-db", out var msgDbDep))
                            msgDbDep.Condition = "service_healthy";
                        // Gate API startup on scylla being CQL-ready, not merely on its container
                        // having entered the running state. Without this, the bootstrapper's
                        // `up` command (which doesn't run db-init and therefore doesn't pre-warm
                        // scylla itself) can race the API into scylla before the cluster has
                        // finished gossip-bootstrap, producing "connection refused on 9042" and
                        // a crash on the very first ScyllaMigrationService.StartingAsync call.
                        if (service.DependsOn.TryGetValue("scylla", out var scyllaDep))
                            scyllaDep.Condition = "service_healthy";
                        if (service.DependsOn.TryGetValue("cassandra", out var cassandraDep))
                            cassandraDep.Condition = "service_healthy";
                    });
                ConfigureApiCommon(apiContainer);
                ConfigureApiSelfHostEnv(apiContainer);
                foreach (var owner in cqlEndpointOwners)
                    apiContainer.WaitFor(owner);
            }
            else
            {
                var apiProject = builder.AddProject<Projects.Interfold_Api>("interfold-api")
                    .WithHttpEndpoint(port: apiHttpPort, targetPort: apiContainerHttpPort, name: "http")
                    .WithHttpsEndpoint(port: apiHttpsPort, targetPort: apiContainerHttpsPort, name: "https")
                    .WithHttpHealthCheck("/health/ready", endpointName: "http")
                    .WithExternalHttpEndpoints()
                    .WaitFor(msgDbResource)
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["scylla", "postgres", "api"];
                        service.Healthcheck = new Healthcheck
                        {
                            Test = ["CMD", "curl", "-f", $"http://localhost:{apiContainerHttpPort}/health/ready"],
                            Interval = "15s",
                            Timeout = "5s",
                            Retries = 10,
                            StartPeriod = "20s"
                        };
                        if (service.DependsOn.TryGetValue("msg-db", out var msgDbDep))
                            msgDbDep.Condition = "service_healthy";
                        if (service.DependsOn.TryGetValue("scylla", out var scyllaDep))
                            scyllaDep.Condition = "service_healthy";
                        if (service.DependsOn.TryGetValue("cassandra", out var cassandraDep))
                            cassandraDep.Condition = "service_healthy";
                    });
                ConfigureApiCommon(apiProject);
                foreach (var owner in cqlEndpointOwners)
                    apiProject.WaitFor(owner);
            }
        }

        // --- Octocon Web (pre-built container, optional) ---
        var includeWeb = !string.Equals(builder.Configuration["Parameters:include-web"], "false", StringComparison.OrdinalIgnoreCase);
        // Opt-in HTTPS termination via the official nginx image's envsubst-on-templates
        // entrypoint. When on, the bootstrapper bind-mounts the issued leaf cert/key and a
        // generated nginx template into the container so port 443 terminates TLS without
        // requiring a custom image build. The dev `aspire run` flow leaves this off and
        // ships the upstream image unmodified.
        var webTls = ParseToggle(builder.Configuration["Parameters:web-tls"], fallback: false);
        if (includeWeb)
        {
            var web = builder.AddContainer("octocon-web", "ghcr.io/azyyyyyy/octocon-wasm", "latest")
                .WithContainerNetworkAlias("octocon-web");

            if (webTls)
            {
                // Server name has to be passed through configuration because Configure() doesn't
                // see the operator's BootstrapConfig directly. PublishPhase injects it from
                // BootstrapConfig.Deployment.Domains[0]; fall back to a wildcard so dev callers
                // that flip the toggle on without populating the parameter still get a working
                // server block (nginx accepts `_` as a catch-all).
                var serverName = builder.Configuration["Parameters:web-server-name"];
                if (string.IsNullOrWhiteSpace(serverName)) serverName = "_";

                web = web
                    .WithHttpEndpoint(port: webHttpPort, targetPort: 80, name: "http")
                    .WithHttpsEndpoint(port: webHttpsPort, targetPort: 443, name: "https")
                    .WithBindMount("../../certs", "/certs", isReadOnly: true)
                    .WithBindMount(
                        "../../web/nginx/default.conf.template",
                        "/etc/nginx/templates/default.conf.template",
                        isReadOnly: true)
                    .WithEnvironment("NGINX_SERVER_NAME", serverName)
                    .WithEnvironment("NGINX_SSL_CERT_FILE", "/certs/leaf.crt")
                    .WithEnvironment("NGINX_SSL_KEY_FILE", "/certs/leaf.key")
                    // The default envsubst step in the upstream nginx image substitutes every
                    // env var it can resolve, which would clobber nginx's own runtime
                    // variables (`$host`, `$uri`, ...). Restrict it to the NGINX_* names we
                    // actually want substituted.
                    .WithEnvironment("NGINX_ENVSUBST_FILTER", "^NGINX_")
                    .WithHttpHealthCheck("/", endpointName: "http")
                    // Must come AFTER the endpoint registrations - Aspire's external-endpoint
                    // pass walks the resource's current endpoint set, so calling this before
                    // WithHttpEndpoint / WithHttpsEndpoint produces a service with only
                    // `expose:` and no `ports:` in the emitted compose.
                    .WithExternalHttpEndpoints()
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["api"];
                        service.                    Healthcheck = new Healthcheck
                        {
                            // `-k` because the leaf is signed by the bootstrapper's private root
                            // CA which the container doesn't trust by default; the probe just
                            // verifies nginx is serving over TLS.
                            Test = ["CMD", "curl", "-kf", "https://localhost:443/"],
                            Interval = "15s",
                            Timeout = "5s",
                            Retries = 5,
                            StartPeriod = "10s"
                        };
                    });
            }
            else
            {
                web = web
                    .WithHttpEndpoint(port: webHttpPort, targetPort: 80, name: "http")
                    .WithHttpEndpoint(port: webHttpsPort, targetPort: 8080, name: "https")
                    .WithHttpHealthCheck("/", endpointName: "http")
                    .WithExternalHttpEndpoints()
                    .PublishAsDockerComposeService((_, service) =>
                    {
                        service.Networks = ["api"];
                        service.                    Healthcheck = new Healthcheck
                        {
                            Test = ["CMD", "curl", "-f", "http://localhost:80/"],
                            Interval = "15s",
                            Timeout = "5s",
                            Retries = 5,
                            StartPeriod = "10s"
                        };
                    });
            }
            _ = web;
        }
    }

    /// <summary>
    /// Splits an image reference like <c>ghcr.io/foo/bar:1.2.3</c> or <c>interfold-api:test</c>
    /// into (image, tag). Tags only - SHA digests would need a different code path.
    /// </summary>
    private static (string Image, string Tag) SplitImageRef(string reference)
    {
        // Find the LAST colon that isn't inside the registry-port portion (e.g. localhost:5000/foo:tag).
        // The tag separator is the last colon after the last slash, since any colon before the last slash
        // belongs to the registry hostname.
        var lastSlash = reference.LastIndexOf('/');
        var lastColon = reference.LastIndexOf(':');
        if (lastColon > lastSlash && lastColon > 0)
        {
            return (reference[..lastColon], reference[(lastColon + 1)..]);
        }
        // No tag specified - default to "latest".
        return (reference, "latest");
    }
}
